import Header1 from "../images/header.webp";
import Header2 from "../images/header2.png";
import Header3 from "../images/header3.png";
export const sliderItems = [
	{
		id: 1,
		img: Header1,
		title: "SUMMER SALE",
		desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
		bg: "f5fafd",
	},
	{
		id: 2,
		img: Header2,
		title: "AUTUMN COLLECTION",
		desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
		bg: "fcf1ed",
	},
	{
		id: 3,
		img: Header3,
		title: "LOUNGEWEAR LOVE",
		desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
		bg: "fbf0f4",
	},
];

export const categories = [
	{
		id: 1,
		img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
		title: "WOMAN SPECIAL!",
		cat: "woman",
	},
	{
		id: 2,
		img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
		title: "LOUNGEWEAR ",
		cat: "coat",
	},
	{
		id: 3,
		img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
		title: "LIGHT JACKETS",
		cat: "jacket",
	},
];
export const popularProducts = [
	{
		title: "Guitar Tee",
		desc: "Men's vintage-style graphic T-shirt.",
		img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
		categories: ["men", "tshirt"],
		size: ["S", "M", "L"],
		color: ["red", "green", "blue"],
		price: 29.99,
		inStock: true,
	},
	{
		title: "Denim Jeans",
		desc: "Classic blue denim jeans for all-day comfort.",
		img: "https://www.pngarts.com/files/4/Denim-PNG-Pic.png",
		categories: ["men", "jeans"],
		size: ["S", "M", "L"],
		color: ["red", "green", "blue"],
		price: 49.99,
		inStock: true,
	},
	{
		title: "Prada Shirt",
		desc: "Premium Prada slim fit cotton shirt.",
		img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
		categories: ["men", "shirt"],
		size: ["S", "M", "L"],
		color: ["red", "green", "blue"],
		price: 109.99,
		inStock: true,
	},
	{
		title: "Summer Dress",
		desc: "Women's lightweight summer dress.",
		img: "https://www.pngarts.com/files/1/Summer-Clothes-For-Women-PNG-Image-Background.png",
		categories: ["women", "dress"],
		size: ["S", "M", "L"],
		color: ["red", "green", "blue"],
		price: 39.99,
		inStock: true,
	},
	{
		title: "Tote Bag",
		desc: "Eco-friendly reusable tote bag.",
		img: "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
		categories: ["bag", "accessory"],
		size: [],
		color: ["red", "green", "blue"],
		price: 14.99,
		inStock: true,
	},
	{
		title: "Chill Cap",
		desc: "Casual vintage chill cap.",
		img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
		categories: ["cap", "accessory"],
		size: [],
		color: ["red", "green", "blue"],
		price: 19.99,
		inStock: true,
	},
	{
		title: "Black Jacket",
		desc: "Stylish black leather jacket.",
		img: "https://www.pngarts.com/files/5/Black-Jacket-Download-PNG-Image.png",
		categories: ["jacket", "men"],
		size: ["S", "M", "L"],
		color: ["red", "green", "blue"],
		price: 89.99,
		inStock: true,
	},
	{
		title: "Women Jacket",
		desc: "Trendy women's winter jacket.",
		img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
		categories: ["jacket", "women"],
		size: ["S", "M", "L"],
		color: ["red", "green", "blue"],
		price: 74.99,
		inStock: true,
	},
];

